# syntax=docker/dockerfile:1

FROM python:3.11-slim-bookworm

RUN pip3 install --upgrade pip

# get curl for healthchecks and build dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl jq build-essential pkg-config \
        default-libmysqlclient-dev \
        libffi-dev libcairo2-dev libpango1.0-dev libgdk-pixbuf2.0-dev shared-mime-info \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app
RUN pip3 install -r requirements.txt
EXPOSE 5000

ENV FLASK_APP=app.py

#CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]

CMD ["python", "-u", "app.py"]